# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
from UseGuide1 import Ui_Dialog
from UG import Example
from Minimum import Ui1_Dialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        MainWindow.setWindowState(Qt.WindowMaximized)

        self.ui = MainWindow  # 命名窗口

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:0.568, x2:1, y2:0, stop:0 rgba(63, 166, 176, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(-10, 180, 921, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setStyleSheet("background-image: url(:/123/图片1.png);")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.action_UseGuide = QtWidgets.QAction(MainWindow)
        self.action_UseGuide.setObjectName("action_UseGuide")
        self.action_UseGraph = QtWidgets.QAction(MainWindow)
        self.action_UseGraph.setObjectName("action_UseGraph")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_SaveAs = QtWidgets.QAction(MainWindow)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.action_Minimum = QtWidgets.QAction(MainWindow)
        self.action_Minimum.setObjectName("action_Minimum")
        self.action_DMP = QtWidgets.QAction(MainWindow)
        self.action_DMP.setObjectName("action_DMP")
        self.action_RA = QtWidgets.QAction(MainWindow)
        self.action_RA.setObjectName("action_RA")
        self.action_CheckMinimum = QtWidgets.QAction(MainWindow)
        self.action_CheckMinimum.setObjectName("action_CheckMinimum")
        self.action_CheckDMP = QtWidgets.QAction(MainWindow)
        self.action_CheckDMP.setObjectName("action_CheckDMP")
        self.action_CheckRA = QtWidgets.QAction(MainWindow)
        self.action_CheckRA.setObjectName("action_CheckRA")
        self.menu.addAction(self.action_New)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Open)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Save)
        self.menu.addSeparator()
        self.menu.addAction(self.action_SaveAs)
        self.menu_2.addAction(self.action_UseGuide)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_UseGraph)
        self.menu_3.addAction(self.action_Minimum)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_DMP)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_RA)
        self.menu_4.addAction(self.action_CheckMinimum)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_CheckDMP)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_CheckRA)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.action_UseGuide.triggered.connect(self.UseGuide_1)

        self.action_Minimum.triggered.connect(self.Minimum)
        # 连接信号

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def UseGuide_1(self):  # 定义槽函数
        self.ui.hide()
        dialog1 = QtWidgets.QDialog()
        UseGuide1 = Ui_Dialog()
        UseGuide1.setupUi(dialog1)
        dialog1.show()
        dialog1.exec_()
        dialog1.show()
        dialog1.exec_()
        self.ui.show()

    def Minimum(self):  # 定义槽函数
        self.ui.hide()
        dialog3 = QtWidgets.QDialog()
        UseGuide1 = Ui1_Dialog()
        UseGuide1.setupUi(dialog3)
        dialog3.show()
        dialog3.exec_()
        self.ui.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络可靠性"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "创建网络"))
        self.menu_3.setTitle(_translate("MainWindow", "计算"))
        self.menu_4.setTitle(_translate("MainWindow", "查看结果"))
        self.action_UseGuide.setText(_translate("MainWindow", "使用向导创建网络"))
        self.action_UseGraph.setText(_translate("MainWindow", "图形化绘制网络"))
        self.action_New.setText(_translate("MainWindow", "新建"))
        self.action_Open.setText(_translate("MainWindow", "打开"))
        self.action_Save.setText(_translate("MainWindow", "保存"))
        self.action_SaveAs.setText(_translate("MainWindow", "另存为"))
        self.action_Minimum.setText(_translate("MainWindow", "最小路集搜索"))
        self.action_DMP.setText(_translate("MainWindow", "D-MP搜索"))
        self.action_RA.setText(_translate("MainWindow", "可靠性评估"))
        self.action_CheckMinimum.setText(_translate("MainWindow", "查看最小路集搜索结果"))
        self.action_CheckDMP.setText(_translate("MainWindow", "查看D-MP搜索结果"))
        self.action_CheckRA.setText(_translate("MainWindow", "查看可靠性评估结果"))


import q_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
